class createForm {
  elements = {
    createMarketForm: () => cy.get('[data-test="createMarketForm"]'),
    createMarketHeader: () => cy.get('[data-test="createMarketHeader"]'),
    marketNameLabel: () => cy.get('[data-test="1. Market name"]'),
    slugField: () => cy.get('[data-test="slugFieldInput"]'),
    questionLabel: () => cy.get('[data-test="2. Market name / Question *"]'),
    questionField: () => cy.get('[data-test="marketQuestionInput"]'),
    tagChoices: () => cy.get('[data-test="tagChoices"]'),
    tagNorthAmerica: () => cy.get('[data-test="tag"]'),
    marketEndsLabel: () => cy.get('[data-test="3. Market ends *"]'),
    marketEndsOption: () => cy.get('[data-test="marketEndField"]'),
    Enddate: () => cy.get('[data-test="marketEndTypeSwitch"]'),
    Endblock: () => cy.get('[data-test="marketEndTypeSwitch"]'),
    calendericon: () => cy.get('[data-test="calendarIcon"]'),
    currentDate: () => cy.get(".rdtToday"),
    outcomesLabel: () => cy.get('[data-test="4. Outcomes *"]'),
    multipleOutcomes: () => cy.get('[data-test="Multiple outcomes"]'),
    outcomesSwitch: () => cy.get('[data-test="switchButton"]'),
    rangeOfOutcomes: () => cy.get('[data-test="Range of outcomes"]'),
    multipleOutcomesInput0: () => cy.get('[data-test="outComeInput"]'),
    multipleOutcomesTicker0: () => cy.get('[data-test="outComeTicker"]'),
    multipleOutcomesInput1: () => cy.get('[data-test="outComeInput"]'),
    multipleOutcomesTicker1: () => cy.get('[data-test="outComeTicker"]'),
    rangeOfOutcomeMinInput: () =>
      cy.get('[data-test="minRangeValueInput"]'),
    rangeOfOutcomeMaxInput: () =>
      cy.get('[data-test="maxRangeValueInput"]'),
    rangeOfOutcomeTicker: () =>
      cy.get('[data-test="rangeTickerInput"]'),
    oracleLabel: () => cy.get('[data-test="5. Oracle *"]'),
    oracleInput: () => cy.get('[data-test="oracleInput"]'),
    marketDescriptionLabel: () => cy.get('[data-test="6. Market Description"]'),
     marketDescriptionTextbox: () => cy.get('[data-test="marketDescriptionInput"]'),
    permissionlessLabel: () => cy.get('[data-test="Permissionless"]'),
    permissionlessSwitch: () => cy.get('[data-test="switchButton"]'),
    advisedLabel: () => cy.get('[data-test="Advised"]'),
    liquiditypoolon: () => cy.get('[data-test="liquidityButton"]'),
    liquiditypooloff: () => cy.get('[data-test="liquidityButton"]'),
    createMarketButton: () => cy.get("[data-test=createMarketSubmitButton]"),
    totalCost: () => cy.get('[data-test="totalCost"]'),
    notificationMessage: () => cy.get('[data-test="notificationMessage"]'),
  };
}
module.exports = new createForm();
