name: "Zeitgeist CI"
on:
  push:
    branches: [ "CI_Task_133" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clean workspace
        uses: AutoModality/action-clean@v1
      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Node Packages
        if: steps.npm-cache.node_modules.cache-hit != 'true'
        run: |
          npm install --legacy-peer-deps
      # - name: Run front end
      #   run: npm start -p 3000 &
      # Add or replace test runners here
          node_modules/.bin/cypress run --headed cypress/integration/*.js