name: Unit Tests
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
